### ISSUE TITLE
Vast majority of my funds swept to mctriva address

### ISSUE THREAD

**Issue by BlockchainEconomy** [mctrivia/DigiSweep#11]
Greetings, 

May I start by saying thank you for your sweeping service, it has helped solve a big problem for me. 

However, it has created an even bigger on that should be easy to solve. 

I was using the mctriva sweep service and the vast majority of my funds got sent to the donation address somehow. 

While I dont mind making a donation, this is a catastrophic loss due to the amount. 

100081.66903601 DGB were sent to the donation address without my consent. Perhaps I made an error, but the last sweeps I did, didnt have this problem. 

Transaction #
5aefb68e61269b01bb833e10dae1c4221efc31ed254927ebc5242d98f172733d

Link:
https://digibyteblockexplorer.com/address/D9RVKBjzRvnzUUTHxZBNZ3kfAHrmci1v76

Would you please kindly refund me 99081.66903601 DGB to address:
dgb1qr6c2jl47pnguvuaf20kku20p5vvs40skkx079p

I would be happy to leave 1000 DGB as a donation. 

Thank you kindly for your help and consideration..

Kind regards

WF

**Comment by BlockchainEconomy** [comment]
Am I going to get my funds back like you did in 2019 for another gentleman? I hope you can understand how stressful this is, the other guy had like 50 DGB, my loss is over $10,000. Its frustrating as I did 2 other wallets before the gargantic loss and the donations were reasonable.. 

Please reply. This is catastrophic.

**Comment by mctrivia** [comment]
Sorry just noticed the post now.

DigiSweep moved to DigiSweep.digiassetX.com will send you refund as asked for.

**Comment by mctrivia** [comment]
Txid of refund: c5d11df568c43b7857595c7a8ebd187f2ff741adf7a74750c13ec891e945f05d

**Comment by BlockchainEconomy** [comment]
Thank you mctrivia, return received. Your honesty and integrity is greatly appreciated! God bless!
